language: node_js
cache:
  directories:
    - ~/.npm
    - ~/.cache
notifications:
  email: true
node_js:
  - '8'
before_script:
  - npm ci
script:
  - npm run lint
  - npm test -- --record
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
