language: node_js
cache:
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
    - $(npm bin)/cypress verify
notifications:
  email: true
node_js:
  - '10'
script:
  - npm run lint
  - npm test -- --record
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
